### PR TITLE
Feature/9 roster

### PR DESCRIPTION
**Pull request by brooksduggan**
New Features within Roster:

- Update Bio feature

- Update Proficiency feature

- Delete Comment/Discipline feature

- Compatibility with mobile devices in formatting

- Added documentation

### CODE REVIEW

**Comment by ffroggy** [comment]
@switchroute 
Hi Brooks! Nice job, but unfortunately this isn't ready to merge yet :( See how the 'files changed' section on this pull request has 481 changed files? It means you're attempting to commit a whole bunch of files that you didn't edit.
You're gonna have to go through and make sure all those .pyc files aren't getting committed! That means manually deleting all the __pycache__ folders and every .pyc file that's being tracked (unfortunately, you will probably have to do this manually). Make sure that your .gitignore file is set up to ignore **/*.pyc files and __pycache__ folders too, and then recommit and let me know when you've got it done! Good luck :)

**Review by ffroggy — CHANGES_REQUESTED** [review]
See my earlier comment

**Review by ffroggy — APPROVED** [review]

**Review by joshuawoodapu — COMMENTED** [review]
I'm not sure why there are shift covers changes in this branch?

**Comment by brooksduggan** [comment]
I'm not sure why there are any changes to shifts either.

**Comment by brooksduggan** [comment]
Seems that I fixed the merge conflicts with the Shifts branch.  So if you could review over it once more and Approve/Comment  it, that'd be great!

**Review by ffroggy — APPROVED** [review]
Looks great! Thanks brooks

**Pull request merged**
